[book]
authors = ["JiaJun Yim"]
language = "en"
multilingual = false
src = "."
title = "dotfiles"

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[preprocessor.toc]
marker = "[[_TOC_]]"
command = "mdbook-toc"
renderer = ["html"]
